"project_id": "ADD_PROJECT_ID"
"api_token": "ADD_PROJECT_API_TOKEN"
"base_path": "./src/locales"
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": false

files: [
  {
    "source": "/en/navbar.json",
    "translation": "/%two_letters_code%/navbar.json",
  },
  
  # Add other languages files here
]