"project_id": "645992"
"api_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6IjhkNGI2ZjY2ZGJkYzdjNDc4NzU2OWJlMzFiZWFmOTA5YzJlY2YyMTAzODBiYWEzNjk1YmJjZjQzMDFhOWRhNWUwZDJlNzUwMDM3MDIxNThiIiwiaWF0IjoxNzA3MTMxOTQ1LjAwOTU5MywibmJmIjoxNzA3MTMxOTQ1LjAwOTU5NSwiZXhwIjoxNzM4NjY3OTQ0Ljk0NDUyOSwic3ViIjoiMTYyMjAxNzAiLCJzY29wZXMiOlsicHJvamVjdCJdLCJkb21haW4iOm51bGwsImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.RlAsndALezFxf9ZYlv9AYzBfnSu0dpmilnnm4Wqe3JXKciJxJG-QMm4rJH5xiNYOf4L-l1jKMLpibusEH2sl_TlJ21tb-rc4m8VdnCeYF-LqCYs6Ul8ziy1RnaACtCqEV0TFW_RApTuBzieP6JdaTMKN11E869PN3_CdZ8V0w5qWKDB329uqD49KYWJsfeQ-s17g14FZmhXc1NnFzJe417VbMsVVuPMyGAWyX1lalhoClk8ID7pdb6qfUqa72XsJqRPfFCZG0P2WfG1e2Kzldgudm1lE4JVSXFi7ub_QYdtmcb9-4QMXqu9HyzbJC8rT9mF387tnV9DzAutmr3faUVC0IIzxZJleW1T9Jvq6KOm9BxM8ybu9_V0OYjA5QLpLb_1BrP87USDBMrYEkd70AZws_ZVHVTMOsMktLk6YDtqQCLGfPLGXt-Fqtd60BEIcXy-sX8K9n7yTwGmSmHp2_IcjFj9GAXk9JgxUjdEM16E0Fxug2mMsaeldEEOpfJlMXQaJjvuK-OJ0-4mTl4DJywD8LN6q-yLxwZbjhCemGWxzdMvEnwn4uceR4_-w82ycHdvsRRIviVuDw9IQ_hFE6u9MtEv3-arWsbN42oLC48o0qcROHcFvvCgW7Pa9rOuOAwb981JJBQvEZ2XSrxkTFpc8pvMvpHxaYNb5z6j3oPc"
"base_path": "./src/locales"
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": false

files: [
  {
    "source": "/en/navbar.json",
    "translation": "/%two_letters_code%/navbar.json",
  },
  {
    "source": "/en/footer.json",
    "translation": "/%two_letters_code%/footer.json",
  },
  {
    "source": "/en/table.json",
    "translation": "/%two_letters_code%/table.json",
  },
]