name: Publish Package

on:
  pull_request:
    types:
      - unlabeled
    branches:
      - 'master'

jobs:
  starter:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord build start
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Build cly-core Started
          webhookUrl: https://discord.com/api/webhooks/1179688868849647687/aejDFoYzwsQIR7a1L-S4PvM_dFetoUJGNUsLn8ToUNOeOUzoje9GZ-EMOc4EN9iBkaXL
  
  build-icons:
    needs: starter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean Package.Json
        run: scripts/clean-package.sh

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-        
        
      - name: Install dependencies
        run: yarn install

      - name: make SVGs
        run: yarn svgr

      - name: build Icons
        run: npm run rollup:icons

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: icons-dist
          path: dist/**/*

  build-utils:
    needs: starter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clean Package.Json
      run: scripts/clean-package.sh

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install

    - name: build Package
      run: npm run rollup:utils


    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: utils-dist
        path: dist/**/*

  build-hooks:
    needs: starter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clean Package.Json
      run: scripts/clean-package.sh

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install

    - name: build Package
      run: npm run rollup:hooks


    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hooks-dist
        path: dist/**/*

  build-ui:
    needs: starter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clean Package.Json
      run: scripts/clean-package.sh

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install

    - name: build Package
      run: npm run rollup:ui

    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ui-dist
        path: dist

  publish-to-npm-registry:
    needs: [build-ui,build-icons,build-utils,build-hooks]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
      
      - name: move hooks
        run: mv hooks dist/hooks

      - name: move utils
        run: mv hooks dist/utils

      - name: move icons
        run: mv hooks dist/icons

      - name: Display structure of downloaded files
        run: ls -R dist

      - name: Clean Package.Json
        run: scripts/clean-package.sh

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
  
      - name: Install dependencies
        run: yarn install
  
      - name: post Build Helper
        run: npm run post:build

      - name: Publish to GitHub npm Registry
        run: npm publish ./dist

      - name: Notify Discord build Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Build cly-core success
          webhookUrl: https://discord.com/api/webhooks/1179688868849647687/aejDFoYzwsQIR7a1L-S4PvM_dFetoUJGNUsLn8ToUNOeOUzoje9GZ-EMOc4EN9iBkaXL

      - name: Notify Discord build fail
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Build cly-core error
          webhookUrl: https://discord.com/api/webhooks/1179688868849647687/aejDFoYzwsQIR7a1L-S4PvM_dFetoUJGNUsLn8ToUNOeOUzoje9GZ-EMOc4EN9iBkaXL