name: Publish Package

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  starter:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  publish-to-npm-registry:
    needs: starter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
      
      - name: move hooks
        run: mv hooks dist/hooks

      - name: move utils
        run: mv hooks dist/utils

      - name: move icons
        run: mv hooks dist/icons

      - name: Display structure of downloaded files
        run: ls -R dist

      - name: Clean Package.Json
        run: scripts/clean-package.sh

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
  
      - name: Install dependencies
        run: yarn install
  
      - name: post Build Helper
        run: npm run post:build

      - name: Publish to GitHub npm Registry
        run: npm publish ./dist

  auto-merge:
    needs: publish-to-npm-registry
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq -r ".pull_request.number" < "$GITHUB_EVENT_PATH")
          gh pr merge $PR_NUMBER --repo ${{ github.repository }} --squash --admin
